package context

import (
	"fmt"
	"sort"
	"strings"

	"github.com/HeyMax/agentspec/internal/spec"
)

// RenderMarkdown produces a Markdown document from a FeatureSpec filtered by the given RoleConfig.
func RenderMarkdown(s *spec.FeatureSpec, role RoleConfig) string {
	var b strings.Builder

	b.WriteString(fmt.Sprintf("# Feature: %s\n", s.DisplayName))
	b.WriteString(fmt.Sprintf("> %s Agent Context — Generated by agentspec\n\n", role.Name))

	if s.Description != "" {
		b.WriteString(s.Description + "\n\n")
	}

	if role.IncludeModels && len(s.Models) > 0 {
		renderModels(&b, s, role)
	}

	if role.IncludeEnums && len(s.Enums) > 0 {
		renderEnums(&b, s)
	}

	if role.IncludeBehaviors && len(s.Behaviors) > 0 {
		renderBehaviors(&b, s, role)
	}

	if role.IncludeAPIs && len(s.APIs) > 0 {
		renderAPIs(&b, s, role)
	}

	if role.IncludeUI && len(s.UI.Pages) > 0 {
		renderUI(&b, s)
	}

	if role.IncludeAcceptance && len(s.Acceptance) > 0 {
		renderAcceptance(&b, s)
	}

	return b.String()
}

func renderModels(b *strings.Builder, s *spec.FeatureSpec, role RoleConfig) {
	b.WriteString("## Data Models\n\n")

	names := sortedKeys(s.Models)
	for _, name := range names {
		model := s.Models[name]
		b.WriteString(fmt.Sprintf("### %s\n\n", name))

		if model.Description != "" {
			b.WriteString(model.Description + "\n\n")
		}

		if len(model.Fields) > 0 {
			if role.ModelsTypeOnly {
				b.WriteString("| Field | Type | Required | Description |\n")
				b.WriteString("|-------|------|----------|-------------|\n")
			} else {
				b.WriteString("| Field | Type | Required | Description | Constraints |\n")
				b.WriteString("|-------|------|----------|-------------|-------------|\n")
			}

			fieldNames := sortedKeys(model.Fields)
			for _, fn := range fieldNames {
				f := model.Fields[fn]
				req := "no"
				if f.Required {
					req = "yes"
				}
				if role.ModelsTypeOnly {
					b.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s |\n", fn, f.Type, req, f.Description))
				} else {
					b.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s | %s |\n", fn, f.Type, req, f.Description, formatConstraints(f.Constraints)))
				}
			}
			b.WriteString("\n")
		}

		if model.States != nil && !role.ModelsTypeOnly {
			renderStateMachine(b, model.States)
		}

		if len(model.Indexes) > 0 && !role.ModelsTypeOnly {
			b.WriteString("**Indexes:**\n\n")
			for _, idx := range model.Indexes {
				unique := ""
				if idx.Unique {
					unique = " (unique)"
				}
				b.WriteString(fmt.Sprintf("- [%s]%s\n", strings.Join(idx.Fields, ", "), unique))
			}
			b.WriteString("\n")
		}
	}
}

func renderStateMachine(b *strings.Builder, sm *spec.StateMachine) {
	b.WriteString(fmt.Sprintf("#### State Machine: %s\n\n", sm.Field))
	b.WriteString(fmt.Sprintf("**Values:** %s\n\n", strings.Join(sm.Values, ", ")))

	if len(sm.Transitions) > 0 {
		b.WriteString("**Transitions:**\n\n")
		keys := sortedKeys(sm.Transitions)
		for _, from := range keys {
			targets := sm.Transitions[from]
			b.WriteString(fmt.Sprintf("- `%s` → %s\n", from, formatList(targets)))
		}
		b.WriteString("\n")
	}
}

func renderEnums(b *strings.Builder, s *spec.FeatureSpec) {
	b.WriteString("## Enums\n\n")

	names := sortedKeys(s.Enums)
	for _, name := range names {
		enum := s.Enums[name]
		b.WriteString(fmt.Sprintf("### %s\n\n", name))

		if enum.Description != "" {
			b.WriteString(enum.Description + "\n\n")
		}

		b.WriteString("| Name | Value | Description |\n")
		b.WriteString("|------|-------|-------------|\n")
		for _, v := range enum.Values {
			b.WriteString(fmt.Sprintf("| %s | `%v` | %s |\n", v.Name, v.Value, v.Description))
		}
		b.WriteString("\n")
	}
}

func renderBehaviors(b *strings.Builder, s *spec.FeatureSpec, role RoleConfig) {
	b.WriteString("## Behaviors\n\n")

	ids := sortedKeys(s.Behaviors)
	for _, id := range ids {
		beh := s.Behaviors[id]
		b.WriteString(fmt.Sprintf("### %s: %s\n\n", id, beh.Description))

		if beh.Actor != "" || beh.TargetModel != "" {
			parts := []string{}
			if beh.Actor != "" {
				parts = append(parts, fmt.Sprintf("**Actor**: %s", beh.Actor))
			}
			if beh.TargetModel != "" {
				parts = append(parts, fmt.Sprintf("**Target**: %s", beh.TargetModel))
			}
			b.WriteString(strings.Join(parts, " | ") + "\n\n")
		}

		if beh.Idempotent {
			b.WriteString("*Idempotent*")
			if beh.Async {
				b.WriteString(" | *Async*")
			}
			b.WriteString("\n\n")
		} else if beh.Async {
			b.WriteString("*Async*\n\n")
		}

		if role.BehaviorsSummaryOnly {
			continue
		}

		if len(beh.Preconditions) > 0 {
			b.WriteString("**Preconditions:**\n\n")
			for _, p := range beh.Preconditions {
				line := "- " + p.Description
				if p.Check != "" {
					line += fmt.Sprintf(" (`%s`)", p.Check)
				}
				b.WriteString(line + "\n")
			}
			b.WriteString("\n")
		}

		if len(beh.Effects) > 0 {
			b.WriteString("**Effects:**\n\n")
			for _, e := range beh.Effects {
				line := "- " + e.Description
				if e.Mutation != "" {
					line += fmt.Sprintf(" (`%s`)", e.Mutation)
				}
				b.WriteString(line + "\n")
			}
			b.WriteString("\n")
		}

		if len(beh.Errors) > 0 {
			b.WriteString("**Errors:**\n\n")
			b.WriteString("| Code | HTTP Status | Message |\n")
			b.WriteString("|------|-------------|---------|\n")
			for _, e := range beh.Errors {
				b.WriteString(fmt.Sprintf("| %s | %d | %s |\n", e.Code, e.HTTPStatus, e.Message))
			}
			b.WriteString("\n")
		}

		if role.IncludeCrossImpact && len(beh.CrossImpact) > 0 {
			b.WriteString("**Cross-Impact:**\n\n")
			for _, ci := range beh.CrossImpact {
				b.WriteString(fmt.Sprintf("- **%s**: %s", ci.Target, ci.Description))
				if ci.Effect != "" {
					b.WriteString(fmt.Sprintf(" (`%s`)", ci.Effect))
				}
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
	}
}

func renderAPIs(b *strings.Builder, s *spec.FeatureSpec, role RoleConfig) {
	b.WriteString("## API Endpoints\n\n")

	ids := sortedKeys(s.APIs)
	for _, id := range ids {
		api := s.APIs[id]
		b.WriteString(fmt.Sprintf("### %s %s\n\n", api.Method, api.Path))

		if api.Summary != "" {
			b.WriteString(api.Summary + "\n\n")
		}

		if api.Behavior != "" {
			b.WriteString(fmt.Sprintf("**Behavior:** %s\n\n", api.Behavior))
		}

		authStr := "required"
		if !api.RequiresAuth() {
			authStr = "none"
		}
		b.WriteString(fmt.Sprintf("**Auth:** %s\n\n", authStr))

		if role.APIsSummaryOnly {
			continue
		}

		// Request
		hasRequest := len(api.Request.Params) > 0 || len(api.Request.Query) > 0 || api.Request.Body != nil
		if hasRequest {
			b.WriteString("**Request:**\n\n")

			if len(api.Request.Params) > 0 {
				b.WriteString("*Path params:*\n\n")
				renderParamTable(b, api.Request.Params)
			}
			if len(api.Request.Query) > 0 {
				b.WriteString("*Query params:*\n\n")
				renderParamTable(b, api.Request.Query)
			}
			if api.Request.Body != nil && len(api.Request.Body.Fields) > 0 {
				ct := api.Request.Body.ContentType
				if ct == "" {
					ct = "application/json"
				}
				b.WriteString(fmt.Sprintf("*Body (%s):*\n\n", ct))
				renderParamTable(b, api.Request.Body.Fields)
			}
		}

		// Response
		resp := api.Response
		if resp.Success.Status > 0 || resp.Success.Body != nil {
			b.WriteString("**Response:**\n\n")
			if resp.Success.Status > 0 {
				b.WriteString(fmt.Sprintf("*Success (%d):*\n\n", resp.Success.Status))
			}
			if resp.Success.Body != nil {
				if resp.Success.Body.Type != "" {
					b.WriteString(fmt.Sprintf("Type: `%s`", resp.Success.Body.Type))
					if resp.Success.Body.Pagination {
						b.WriteString(" (paginated)")
					}
					b.WriteString("\n\n")
				}
				if resp.Success.Body.Items != nil {
					b.WriteString(fmt.Sprintf("Items: `%s`\n\n", resp.Success.Body.Items.Type))
				}
				if len(resp.Success.Body.Fields) > 0 {
					renderParamTable(b, resp.Success.Body.Fields)
				}
			}
		}

		if len(resp.Errors) > 0 {
			b.WriteString("*Errors:*\n\n")
			b.WriteString("| Status | Code | Description |\n")
			b.WriteString("|--------|------|-------------|\n")
			for _, e := range resp.Errors {
				b.WriteString(fmt.Sprintf("| %d | %s | %s |\n", e.Status, e.Code, e.Description))
			}
			b.WriteString("\n")
		}
	}
}

func renderUI(b *strings.Builder, s *spec.FeatureSpec) {
	b.WriteString("## UI Pages\n\n")

	names := sortedKeys(s.UI.Pages)
	for _, name := range names {
		page := s.UI.Pages[name]
		b.WriteString(fmt.Sprintf("### %s\n\n", name))

		if page.Title != "" {
			b.WriteString(fmt.Sprintf("**Title:** %s\n\n", page.Title))
		}
		if page.Path != "" {
			b.WriteString(fmt.Sprintf("**Path:** `%s`\n\n", page.Path))
		}
		if page.Type != "" {
			b.WriteString(fmt.Sprintf("**Type:** %s\n\n", page.Type))
		}
		if page.Description != "" {
			b.WriteString(page.Description + "\n\n")
		}
		if page.DataSource != "" {
			b.WriteString(fmt.Sprintf("**Data Source:** %s\n\n", page.DataSource))
		}

		if page.Permissions != nil && len(page.Permissions.Roles) > 0 {
			b.WriteString(fmt.Sprintf("**Permissions:** %s\n\n", strings.Join(page.Permissions.Roles, ", ")))
		}

		if len(page.Components) > 0 {
			b.WriteString("**Components:**\n\n")
			for _, comp := range page.Components {
				label := comp.Type
				if comp.ID != "" {
					label = fmt.Sprintf("%s (`%s`)", comp.Type, comp.ID)
				}
				b.WriteString(fmt.Sprintf("- %s\n", label))
				for _, act := range comp.Actions {
					parts := []string{fmt.Sprintf("trigger: %s", act.Trigger)}
					if act.API != "" {
						parts = append(parts, fmt.Sprintf("api: %s", act.API))
					}
					if act.Confirm {
						parts = append(parts, "confirm: yes")
					}
					b.WriteString(fmt.Sprintf("  - %s\n", strings.Join(parts, ", ")))
				}
			}
			b.WriteString("\n")
		}
	}
}

func renderAcceptance(b *strings.Builder, s *spec.FeatureSpec) {
	b.WriteString("## Acceptance Criteria\n\n")

	for _, ac := range s.Acceptance {
		b.WriteString(fmt.Sprintf("### %s: %s\n\n", ac.ID, ac.Title))

		if ac.Scenario != "" {
			b.WriteString(ac.Scenario + "\n\n")
		}

		if ac.Priority != "" {
			b.WriteString(fmt.Sprintf("**Priority:** %s\n\n", ac.Priority))
		}

		if len(ac.Behaviors) > 0 {
			b.WriteString(fmt.Sprintf("**Behaviors:** %s\n\n", strings.Join(ac.Behaviors, ", ")))
		}

		if len(ac.APIs) > 0 {
			b.WriteString(fmt.Sprintf("**APIs:** %s\n\n", strings.Join(ac.APIs, ", ")))
		}
	}
}

// --- Helpers ---

func renderParamTable(b *strings.Builder, params map[string]spec.ParamField) {
	b.WriteString("| Field | Type | Required | Description |\n")
	b.WriteString("|-------|------|----------|-------------|\n")
	names := sortedKeysPF(params)
	for _, name := range names {
		p := params[name]
		req := "no"
		if p.Required {
			req = "yes"
		}
		b.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s |\n", name, p.Type, req, p.Description))
	}
	b.WriteString("\n")
}

func formatConstraints(c *spec.Constraints) string {
	if c == nil {
		return ""
	}
	var parts []string
	if c.MinLength != nil {
		parts = append(parts, fmt.Sprintf("min_len=%d", *c.MinLength))
	}
	if c.MaxLength != nil {
		parts = append(parts, fmt.Sprintf("max_len=%d", *c.MaxLength))
	}
	if c.Min != nil {
		parts = append(parts, fmt.Sprintf("min=%g", *c.Min))
	}
	if c.Max != nil {
		parts = append(parts, fmt.Sprintf("max=%g", *c.Max))
	}
	if c.Pattern != "" {
		parts = append(parts, fmt.Sprintf("pattern=`%s`", c.Pattern))
	}
	if c.Unique {
		parts = append(parts, "unique")
	}
	if c.Immutable {
		parts = append(parts, "immutable")
	}
	return strings.Join(parts, ", ")
}

func formatList(items []string) string {
	quoted := make([]string, len(items))
	for i, s := range items {
		quoted[i] = "`" + s + "`"
	}
	return strings.Join(quoted, ", ")
}

// sortedKeys returns sorted keys from a map[string]T using generics workaround.
// We provide typed versions for the maps we use.

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func sortedKeysPF(m map[string]spec.ParamField) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
