package cmd

import (
	"fmt"
	"os"
	"strings"

	"github.com/chenzhaohao/agentspec/internal/util"
	"github.com/spf13/cobra"
)

var initDefaults bool

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Create a new spec file interactively",
	Long:  `Interactively create a new AgentSpec YAML file with guided prompts.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		outputFile := "spec.yaml"
		if specFile != "" {
			outputFile = specFile
		}

		if _, err := os.Stat(outputFile); err == nil {
			util.PrintFail(fmt.Sprintf("File %s already exists. Use -f to specify a different path.", outputFile))
			return nil
		}

		var name, displayName, description, owner string
		var models []string
		var wantAPIs, wantUI bool

		if initDefaults {
			name = "my-feature"
			displayName = "My Feature"
			description = "A new feature specification"
			owner = "team"
			models = []string{"Resource"}
			wantAPIs = true
			wantUI = true
		} else {
			util.PrintHeader("AgentSpec — Initialize New Spec")
			fmt.Println()

			name = util.PromptString("Feature name (kebab-case)", "my-feature")
			displayName = util.PromptString("Display name", util.PascalCase(name))
			description = util.PromptString("Description", "")
			owner = util.PromptString("Owner (team/person)", "team")
			models = util.PromptList("Model names", "User, Task, Comment")
			if len(models) == 0 {
				models = []string{"Resource"}
			}
			wantAPIs = util.PromptBool("Generate CRUD API stubs?", true)
			wantUI = util.PromptBool("Generate UI page stubs?", true)
		}

		content := generateSkeleton(name, displayName, description, owner, models, wantAPIs, wantUI)

		if err := os.WriteFile(outputFile, []byte(content), 0644); err != nil {
			return fmt.Errorf("writing spec file: %w", err)
		}

		fmt.Println()
		util.PrintOK(fmt.Sprintf("Created %s", outputFile))
		util.PrintInfo("Next: edit the spec, then run 'agentspec validate' to check it")

		return nil
	},
}

func init() {
	initCmd.Flags().BoolVar(&initDefaults, "defaults", false, "use defaults without prompting")
	rootCmd.AddCommand(initCmd)
}

func generateSkeleton(name, displayName, description, owner string, models []string, wantAPIs, wantUI bool) string {
	var b strings.Builder

	b.WriteString("# Generated by agentspec init\n")
	b.WriteString(fmt.Sprintf("kind: FeatureSpec\nversion: \"1.0\"\nname: %s\n", name))
	b.WriteString(fmt.Sprintf("display_name: %s\n", displayName))
	b.WriteString(fmt.Sprintf("owner: %s\n", owner))
	if description != "" {
		b.WriteString(fmt.Sprintf("description: %s\n", description))
	}
	b.WriteString("\ntags: []\n")

	// Enums section
	b.WriteString("\n# ─── Enums ─────────────────────────────────────────\n")
	b.WriteString("# Define enums for constrained value sets.\n")
	b.WriteString("# enums:\n")
	b.WriteString("#   status:\n")
	b.WriteString("#     description: Resource status\n")
	b.WriteString("#     values:\n")
	b.WriteString("#       - name: active\n")
	b.WriteString("#         value: active\n")
	b.WriteString("#         description: Currently active\n")
	b.WriteString("enums: {}\n")

	// Models section
	b.WriteString("\n# ─── Models ────────────────────────────────────────\n")
	b.WriteString("# Define your data models with fields, constraints, and state machines.\n")
	b.WriteString("models:\n")
	for _, m := range models {
		pascal := util.PascalCase(m)
		b.WriteString(fmt.Sprintf("  %s:\n", pascal))
		b.WriteString(fmt.Sprintf("    description: A %s entity\n", strings.ToLower(m)))
		b.WriteString("    fields:\n")
		b.WriteString("      id:\n")
		b.WriteString("        type: uuid\n")
		b.WriteString("        required: true\n")
		b.WriteString("        description: Unique identifier\n")
		b.WriteString("        constraints:\n")
		b.WriteString("          immutable: true\n")
		b.WriteString("      name:\n")
		b.WriteString("        type: string\n")
		b.WriteString("        required: true\n")
		b.WriteString("        description: Display name\n")
		b.WriteString("        constraints:\n")
		b.WriteString("          min_length: 1\n")
		b.WriteString("          max_length: 200\n")
		b.WriteString("      created_at:\n")
		b.WriteString("        type: datetime\n")
		b.WriteString("        required: true\n")
		b.WriteString("        description: Creation timestamp\n")
		b.WriteString("        constraints:\n")
		b.WriteString("          immutable: true\n")
		b.WriteString("      updated_at:\n")
		b.WriteString("        type: datetime\n")
		b.WriteString("        required: true\n")
		b.WriteString("        description: Last modification timestamp\n")
	}

	// Behaviors section
	b.WriteString("\n# ─── Behaviors ─────────────────────────────────────\n")
	b.WriteString("# Define business operations with preconditions, effects, and errors.\n")
	b.WriteString("behaviors:\n")
	for _, m := range models {
		pascal := util.PascalCase(m)
		kebab := util.KebabCase(m)
		b.WriteString(fmt.Sprintf("  create-%s:\n", kebab))
		b.WriteString(fmt.Sprintf("    description: Create a new %s\n", strings.ToLower(m)))
		b.WriteString("    actor: User\n")
		b.WriteString(fmt.Sprintf("    target_model: %s\n", pascal))
		b.WriteString("    preconditions:\n")
		b.WriteString("      - description: User must be authenticated\n")
		b.WriteString("    effects:\n")
		b.WriteString(fmt.Sprintf("      - description: A new %s is created\n", pascal))
		b.WriteString("    errors:\n")
		b.WriteString("      - code: VALIDATION_ERROR\n")
		b.WriteString("        message: Invalid input data\n")
		b.WriteString("        http_status: 400\n")
	}

	// APIs section
	if wantAPIs {
		b.WriteString("\n# ─── APIs ──────────────────────────────────────────\n")
		b.WriteString("# Define REST API endpoints linked to behaviors.\n")
		b.WriteString("apis:\n")
		for _, m := range models {
			kebab := util.KebabCase(m)
			b.WriteString(fmt.Sprintf("  list-%ss:\n", kebab))
			b.WriteString("    method: GET\n")
			b.WriteString(fmt.Sprintf("    path: /api/%ss\n", kebab))
			b.WriteString(fmt.Sprintf("    summary: List all %ss\n", strings.ToLower(m)))
			b.WriteString("    auth: true\n")
			b.WriteString("    response:\n")
			b.WriteString("      success:\n")
			b.WriteString("        status: 200\n")

			b.WriteString(fmt.Sprintf("  create-%s:\n", kebab))
			b.WriteString("    method: POST\n")
			b.WriteString(fmt.Sprintf("    path: /api/%ss\n", kebab))
			b.WriteString(fmt.Sprintf("    summary: Create a new %s\n", strings.ToLower(m)))
			b.WriteString(fmt.Sprintf("    behavior: create-%s\n", kebab))
			b.WriteString("    auth: true\n")
			b.WriteString("    request:\n")
			b.WriteString("      body:\n")
			b.WriteString("        content_type: application/json\n")
			b.WriteString("        fields:\n")
			b.WriteString("          name:\n")
			b.WriteString("            type: string\n")
			b.WriteString("            required: true\n")
			b.WriteString(fmt.Sprintf("            description: %s name\n", pascal(m)))
			b.WriteString("    response:\n")
			b.WriteString("      success:\n")
			b.WriteString("        status: 201\n")
		}
	}

	// UI section
	if wantUI {
		b.WriteString("\n# ─── UI ────────────────────────────────────────────\n")
		b.WriteString("# Define UI pages with components and actions.\n")
		b.WriteString("ui:\n")
		b.WriteString("  pages:\n")
		for _, m := range models {
			kebab := util.KebabCase(m)
			b.WriteString(fmt.Sprintf("    %s-list:\n", kebab))
			b.WriteString("      type: list\n")
			b.WriteString(fmt.Sprintf("      path: /%ss\n", kebab))
			b.WriteString(fmt.Sprintf("      title: %s List\n", util.PascalCase(m)))
			b.WriteString(fmt.Sprintf("      data_source: list-%ss\n", kebab))
			b.WriteString("      components:\n")
			b.WriteString("        - type: data-table\n")
			b.WriteString("          id: main-table\n")
		}
	}

	// Acceptance section
	b.WriteString("\n# ─── Acceptance Criteria ────────────────────────────\n")
	b.WriteString("# Define testable acceptance criteria linked to behaviors and APIs.\n")
	b.WriteString("acceptance: []\n")

	return b.String()
}

// pascal is a local alias to avoid collision with the model variable
func pascal(s string) string {
	return util.PascalCase(s)
}
