package generate

import (
	"fmt"
	"strings"

	"github.com/chenzhaohao/agentspec/internal/spec"
	"github.com/chenzhaohao/agentspec/internal/util"
)

func generateBackend(s *spec.FeatureSpec, outputDir string) error {
	// Generate model structs
	if len(s.Models) > 0 {
		content := generateModelStructs(s)
		if err := writeFile(outputDir, "models.go", content); err != nil {
			return err
		}
	}

	// Generate handler stubs
	if len(s.APIs) > 0 {
		content := generateHandlers(s)
		if err := writeFile(outputDir, "handlers.go", content); err != nil {
			return err
		}
	}

	// Generate routes
	if len(s.APIs) > 0 {
		content := generateRoutes(s)
		if err := writeFile(outputDir, "routes.go", content); err != nil {
			return err
		}
	}

	// Generate service interface
	if len(s.Behaviors) > 0 {
		content := generateService(s)
		if err := writeFile(outputDir, "service.go", content); err != nil {
			return err
		}
	}

	return nil
}

func generateModelStructs(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n")
	b.WriteString("package models\n\n")

	needsTime := false
	for _, model := range s.Models {
		for _, f := range model.Fields {
			if f.Type == "datetime" {
				needsTime = true
			}
		}
	}
	if needsTime {
		b.WriteString("import \"time\"\n\n")
	}

	for name, model := range s.Models {
		if model.Description != "" {
			b.WriteString(fmt.Sprintf("// %s — %s\n", name, model.Description))
		}
		b.WriteString(fmt.Sprintf("type %s struct {\n", name))

		for fieldName, field := range model.Fields {
			goName := util.PascalCase(fieldName)
			goType := util.GoType(field.Type)
			jsonTag := fieldName
			b.WriteString(fmt.Sprintf("\t%s %s `json:\"%s\" db:\"%s\"`", goName, goType, jsonTag, fieldName))
			if field.Description != "" {
				b.WriteString(fmt.Sprintf(" // %s", field.Description))
			}
			b.WriteString("\n")
		}

		b.WriteString("}\n\n")
	}

	return b.String()
}

func generateHandlers(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n")
	b.WriteString("package handlers\n\n")
	b.WriteString("import \"net/http\"\n\n")

	for name, api := range s.APIs {
		funcName := util.PascalCase(name)
		b.WriteString(fmt.Sprintf("// %s handles %s %s\n", funcName, api.Method, api.Path))
		if api.Summary != "" {
			b.WriteString(fmt.Sprintf("// %s\n", api.Summary))
		}
		b.WriteString(fmt.Sprintf("func %s(w http.ResponseWriter, r *http.Request) {\n", funcName))
		b.WriteString("\t// TODO: implement\n")

		status := api.Response.Success.Status
		if status == 0 {
			status = 200
		}
		if status == 204 {
			b.WriteString(fmt.Sprintf("\tw.WriteHeader(%d)\n", status))
		} else {
			b.WriteString(fmt.Sprintf("\tw.WriteHeader(%d)\n", status))
			b.WriteString("\tw.Write([]byte(`{}`))\n")
		}
		b.WriteString("}\n\n")
	}

	return b.String()
}

func generateRoutes(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n")
	b.WriteString("package routes\n\n")
	b.WriteString("import \"net/http\"\n\n")
	b.WriteString("func RegisterRoutes(mux *http.ServeMux) {\n")

	for name, api := range s.APIs {
		funcName := util.PascalCase(name)
		// Go 1.22+ style pattern
		b.WriteString(fmt.Sprintf("\tmux.HandleFunc(\"%s %s\", handlers.%s)\n", api.Method, api.Path, funcName))
	}

	b.WriteString("}\n")
	return b.String()
}

func generateService(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n")
	b.WriteString("package service\n\n")
	b.WriteString("import \"context\"\n\n")
	b.WriteString("// Service defines the business operations for this feature.\n")
	b.WriteString("type Service interface {\n")

	for name, beh := range s.Behaviors {
		funcName := util.PascalCase(name)
		desc := beh.Description
		if desc != "" {
			b.WriteString(fmt.Sprintf("\t// %s — %s\n", funcName, desc))
		}
		b.WriteString(fmt.Sprintf("\t%s(ctx context.Context) error\n", funcName))
	}

	b.WriteString("}\n")
	return b.String()
}
