package generate

import (
	"fmt"
	"strings"

	"github.com/HeyMax/agentspec/internal/spec"
	"github.com/HeyMax/agentspec/internal/util"
)

func generateFrontend(s *spec.FeatureSpec, outputDir string) error {
	// Generate TypeScript types
	if len(s.Models) > 0 || len(s.Enums) > 0 {
		content := generateTSTypes(s)
		if err := writeFile(outputDir, "types.ts", content); err != nil {
			return err
		}
	}

	// Generate API client
	if len(s.APIs) > 0 {
		content := generateAPIClient(s)
		if err := writeFile(outputDir, "api-client.ts", content); err != nil {
			return err
		}
	}

	// Generate page components
	for pageName, page := range s.UI.Pages {
		content := generatePageComponent(s, pageName, page)
		fileName := util.KebabCase(pageName) + ".tsx"
		if err := writeFile(outputDir, "pages/"+fileName, content); err != nil {
			return err
		}
	}

	return nil
}

func generateTSTypes(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n\n")

	// Enums
	for name, enum := range s.Enums {
		tsName := util.PascalCase(name)
		b.WriteString(fmt.Sprintf("export enum %s {\n", tsName))
		for _, v := range enum.Values {
			enumKey := strings.ToUpper(v.Name)
			b.WriteString(fmt.Sprintf("  %s = '%s',\n", enumKey, v.Value))
		}
		b.WriteString("}\n\n")
	}

	// Interfaces
	for name, model := range s.Models {
		if model.Description != "" {
			b.WriteString(fmt.Sprintf("/** %s */\n", model.Description))
		}
		b.WriteString(fmt.Sprintf("export interface %s {\n", name))

		for fieldName, field := range model.Fields {
			tsType := util.TsType(field.Type)
			optional := ""
			if !field.Required {
				optional = "?"
			}
			comment := ""
			if field.Description != "" {
				comment = fmt.Sprintf(" // %s", field.Description)
			}
			camelName := util.CamelCase(fieldName)
			b.WriteString(fmt.Sprintf("  %s%s: %s;%s\n", camelName, optional, tsType, comment))
		}

		b.WriteString("}\n\n")
	}

	return b.String()
}

func generateAPIClient(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n\n")
	b.WriteString("const BASE_URL = '/api';\n\n")
	b.WriteString("async function request<T>(method: string, path: string, body?: unknown): Promise<T> {\n")
	b.WriteString("  const res = await fetch(path, {\n")
	b.WriteString("    method,\n")
	b.WriteString("    headers: { 'Content-Type': 'application/json' },\n")
	b.WriteString("    body: body ? JSON.stringify(body) : undefined,\n")
	b.WriteString("  });\n")
	b.WriteString("  if (!res.ok) throw new Error(`${res.status}: ${res.statusText}`);\n")
	b.WriteString("  if (res.status === 204) return undefined as T;\n")
	b.WriteString("  return res.json();\n")
	b.WriteString("}\n\n")

	for name, api := range s.APIs {
		funcName := util.CamelCase(name)
		b.WriteString(fmt.Sprintf("/** %s %s", api.Method, api.Path))
		if api.Summary != "" {
			b.WriteString(fmt.Sprintf(" — %s", api.Summary))
		}
		b.WriteString(" */\n")

		// Build params
		var params []string
		for pName, p := range api.Request.Params {
			tsType := util.TsType(p.Type)
			params = append(params, fmt.Sprintf("%s: %s", util.CamelCase(pName), tsType))
		}
		if api.Request.Body != nil && len(api.Request.Body.Fields) > 0 {
			params = append(params, "body: Record<string, unknown>")
		}

		paramStr := strings.Join(params, ", ")

		// Build path with interpolation
		path := api.Path
		for pName := range api.Request.Params {
			path = strings.ReplaceAll(path, "{"+pName+"}", "${"+util.CamelCase(pName)+"}")
		}

		b.WriteString(fmt.Sprintf("export function %s(%s) {\n", funcName, paramStr))

		bodyArg := "undefined"
		if api.Request.Body != nil && len(api.Request.Body.Fields) > 0 {
			bodyArg = "body"
		}

		b.WriteString(fmt.Sprintf("  return request('%s', `%s`, %s);\n", api.Method, path, bodyArg))
		b.WriteString("}\n\n")
	}

	return b.String()
}

func generatePageComponent(s *spec.FeatureSpec, pageName string, page spec.Page) string {
	var b strings.Builder
	componentName := util.PascalCase(pageName)

	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n")
	b.WriteString("import React from 'react';\n\n")

	b.WriteString(fmt.Sprintf("/**\n * %s\n", componentName))
	if page.Title != "" {
		b.WriteString(fmt.Sprintf(" * Title: %s\n", page.Title))
	}
	if page.Description != "" {
		b.WriteString(fmt.Sprintf(" * %s\n", page.Description))
	}
	b.WriteString(fmt.Sprintf(" * Path: %s\n", page.Path))
	b.WriteString(" */\n")

	b.WriteString(fmt.Sprintf("export default function %s() {\n", componentName))
	b.WriteString("  return (\n")
	b.WriteString("    <div>\n")
	b.WriteString(fmt.Sprintf("      <h1>%s</h1>\n", page.Title))

	for _, comp := range page.Components {
		b.WriteString(fmt.Sprintf("      {/* %s: %s */}\n", comp.Type, comp.ID))
		b.WriteString(fmt.Sprintf("      <div data-component=\"%s\" data-id=\"%s\">\n", comp.Type, comp.ID))
		b.WriteString(fmt.Sprintf("        {/* TODO: implement %s component */}\n", comp.Type))
		b.WriteString("      </div>\n")
	}

	b.WriteString("    </div>\n")
	b.WriteString("  );\n")
	b.WriteString("}\n")

	return b.String()
}
