package generate

import (
	"fmt"
	"strings"

	"github.com/HeyMax/agentspec/internal/spec"
	"github.com/HeyMax/agentspec/internal/util"
)

func generateTests(s *spec.FeatureSpec, outputDir string) error {
	// Generate API tests
	if len(s.APIs) > 0 {
		content := generateAPITests(s)
		if err := writeFile(outputDir, "api_test.go", content); err != nil {
			return err
		}
	}

	// Generate acceptance tests
	if len(s.Acceptance) > 0 {
		content := generateAcceptanceTests(s)
		if err := writeFile(outputDir, "acceptance_test.go", content); err != nil {
			return err
		}
	}

	return nil
}

func generateAPITests(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n")
	b.WriteString("package tests\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"net/http\"\n")
	b.WriteString("\t\"net/http/httptest\"\n")
	b.WriteString("\t\"testing\"\n")
	b.WriteString(")\n\n")

	for name, api := range s.APIs {
		testName := "Test" + util.PascalCase(name)
		b.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", testName))
		b.WriteString(fmt.Sprintf("\t// %s %s\n", api.Method, api.Path))
		if api.Summary != "" {
			b.WriteString(fmt.Sprintf("\t// %s\n", api.Summary))
		}
		b.WriteString("\n")

		// Success test
		b.WriteString("\tt.Run(\"success\", func(t *testing.T) {\n")
		b.WriteString(fmt.Sprintf("\t\treq := httptest.NewRequest(%q, %q, nil)\n", api.Method, api.Path))
		b.WriteString("\t\trec := httptest.NewRecorder()\n")
		b.WriteString("\n")
		b.WriteString("\t\t// TODO: call handler\n")
		b.WriteString("\t\t_ = req\n")
		b.WriteString("\t\t_ = rec\n")
		b.WriteString("\n")

		status := api.Response.Success.Status
		if status == 0 {
			status = 200
		}
		b.WriteString(fmt.Sprintf("\t\tif rec.Code != %d {\n", status))
		b.WriteString(fmt.Sprintf("\t\t\tt.Errorf(\"expected status %d, got %%d\", rec.Code)\n", status))
		b.WriteString("\t\t}\n")
		b.WriteString("\t})\n")

		// Error tests
		for _, errResp := range api.Response.Errors {
			errTestName := "error_" + strings.ToLower(errResp.Code)
			b.WriteString(fmt.Sprintf("\n\tt.Run(%q, func(t *testing.T) {\n", errTestName))
			b.WriteString(fmt.Sprintf("\t\t// Expected: %d %s\n", errResp.Status, errResp.Description))
			b.WriteString(fmt.Sprintf("\t\treq := httptest.NewRequest(%q, %q, nil)\n", api.Method, api.Path))
			b.WriteString("\t\trec := httptest.NewRecorder()\n")
			b.WriteString("\n")
			b.WriteString("\t\t// TODO: setup conditions for error case\n")
			b.WriteString("\t\t_ = req\n")
			b.WriteString("\t\t_ = rec\n")
			b.WriteString("\n")
			b.WriteString(fmt.Sprintf("\t\tif rec.Code != http.StatusOK {\n"))
			b.WriteString(fmt.Sprintf("\t\t\t// TODO: assert status %d\n", errResp.Status))
			b.WriteString("\t\t}\n")
			b.WriteString("\t})\n")
		}

		b.WriteString("}\n\n")
	}

	return b.String()
}

func generateAcceptanceTests(s *spec.FeatureSpec) string {
	var b strings.Builder
	b.WriteString("// Code generated by agentspec. DO NOT EDIT.\n")
	b.WriteString("package tests\n\n")
	b.WriteString("import \"testing\"\n\n")

	for _, ac := range s.Acceptance {
		testName := "TestAcceptance_" + util.PascalCase(ac.ID)
		b.WriteString(fmt.Sprintf("// %s: %s\n", ac.ID, ac.Title))
		if ac.Scenario != "" {
			// Wrap scenario text
			b.WriteString("//\n")
			for _, line := range strings.Split(strings.TrimSpace(ac.Scenario), "\n") {
				b.WriteString(fmt.Sprintf("// %s\n", strings.TrimSpace(line)))
			}
		}
		b.WriteString(fmt.Sprintf("func %s(t *testing.T) {\n", testName))

		if len(ac.Behaviors) > 0 {
			b.WriteString(fmt.Sprintf("\t// Behaviors: %s\n", strings.Join(ac.Behaviors, ", ")))
		}
		if len(ac.APIs) > 0 {
			b.WriteString(fmt.Sprintf("\t// APIs: %s\n", strings.Join(ac.APIs, ", ")))
		}

		b.WriteString("\n\t// TODO: implement acceptance test\n")
		b.WriteString("\tt.Skip(\"not implemented\")\n")
		b.WriteString("}\n\n")
	}

	return b.String()
}
